// Zmpl template manifest.
// This file is automatically generated at build time. Manual edits will be discarded.
// This file should _not_ be stored in version control.
pub const templates = struct {
  pub const index = @import(".index.zmpl.compiled.zig");
  pub const users_index = @import("users/.index.zmpl.compiled.zig");
};
